config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :admins, only: [:index]
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :venues
  resources :votes, only: [:create, :update, :destroy]

  resources :venues do
    resources :reviews, except: [:edit, :update, :destroy]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  namespace :api do
    namespace :v1 do
      resources :reviewapi, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mistake.rb
class Mistake < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, presence: true

  belongs_to
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, email: true,
    uniqueness: { message: "An account already exists for that email address!" }

  has_many :reviews
  has_many :votes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def admin?
    role == "admin"
  end
end

app/models/venue.rb
require 'uri'

class Venue < ApplicationRecord
  STATES = [
    ["AK", "Alaska"],
    ["AL", "Alabama"],
    ["AR", "Arkansas"],
    ["AS", "American Samoa"],
    ["AZ", "Arizona"],
    ["CA", "California"],
    ["CO", "Colorado"],
    ["CT", "Connecticut"],
    ["DC", "District of Columbia"],
    ["DE", "Delaware"],
    ["FL", "Florida"],
    ["GA", "Georgia"],
    ["GU", "Guam"],
    ["HI", "Hawaii"],
    ["IA", "Iowa"],
    ["ID", "Idaho"],
    ["IL", "Illinois"],
    ["IN", "Indiana"],
    ["KS", "Kansas"],
    ["KY", "Kentucky"],
    ["LA", "Louisiana"],
    ["MA", "Massachusetts"],
    ["MD", "Maryland"],
    ["ME", "Maine"],
    ["MI", "Michigan"],
    ["MN", "Minnesota"],
    ["MO", "Missouri"],
    ["MS", "Mississippi"],
    ["MT", "Montana"],
    ["NC", "North Carolina"],
    ["ND", "North Dakota"],
    ["NE", "Nebraska"],
    ["NH", "New Hampshire"],
    ["NJ", "New Jersey"],
    ["NM", "New Mexico"],
    ["NV", "Nevada"],
    ["NY", "New York"],
    ["OH", "Ohio"],
    ["OK", "Oklahoma"],
    ["OR", "Oregon"],
    ["PA", "Pennsylvania"],
    ["PR", "Puerto Rico"],
    ["RI", "Rhode Island"],
    ["SC", "South Carolina"],
    ["SD", "South Dakota"],
    ["TN", "Tennessee"],
    ["TX", "Texas"],
    ["UT", "Utah"],
    ["VA", "Virginia"],
    ["VI", "Virgin Islands"],
    ["VT", "Vermont"],
    ["WA", "Washington"],
    ["WI", "Wisconsin"],
    ["WV", "West Virginia"],
    ["WY", "Wyoming"]
  ].freeze

  validates :name, presence: true

  validates :url, format: { with: URI.regexp }, if: 'url.present?'

  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true

  validates :zip, presence: true
  validates :zip, format: {
    with: /[\d]/,
    message: "is not a number"
  }
  validates :zip, length: { is: 5 }

  has_many :reviews

  def self.search(search)
    where("name ILIKE ? OR url ILIKE ? OR address ILIKE ? OR city ILIKE ? OR state ILIKE ? OR zip ILIKE ? OR capacity ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :up_or_down, inclusion: { in: ["upvote", "downvote"] }

  belongs_to :user
  belongs_to :review
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index; end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/reviewapi_controller.rb
class Api::V1::ReviewapiController < Api::V1::BaseController
  def index
    respond_with Review.order(created_at: :desc).limit(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,
      :avatar_url])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @venue = Venue.find(params[:venue_id])
    @review = Review.new
    @ratings_collection = [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]]
  end

  def crea
      @ratings_collection = [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]]
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @venue = @review.venue
    @review.destroy

    redirect_to venue_path(@venue)
  end

  private

  def review_params
    params.require(:review).permit(:title, :cost, :sound_quality, :parking, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: [:edit, :update, :show]
  before_action :authorize_admin, only: [:index, :destroy]
  def index
    @users =
    @user.skip_reconfirmation!
    if @user.save
      flash[:notice] = 'Success! Your profile has been updated.'
      redirect_to @user
    else
      @user.email = params[:user][:email]
      @user.profile_pic_url = params[:user][:profile_pic_url]
      @user.avatar = params[:user][:avatar]
      render :edit
    end
  end

  def destroy
    this_user = User.find(params[:id])
    this_user.destroy

    redirect_to users_path
  end

  def authorize_user
    if !user_signed_in?
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  def authorize_admin
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  def show
    @wizards = Wizard.all
    render :show
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :authorize_admin, only: [:edit, :update, :destroy]

    @venue = Venue.new
    @state_collection = Venue::STATES
  end

  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      flash[:notice] = 'Venue added successfully!'
      redirect_to @venue
    else
      @state_collection = Venue::STATES
      render action: 'new'
    end
  end

  def edit
    @venue = Venue.find(params[:id])
    @state_collection = Venue::STATES
  end

  def update
    @venue = Venue.find(params[:id])
    if @venue.update_attributes(venue_params)
      redirect_to venue_path(@venue)
    else
      @state_collection = Venue::STATES
      render :edit
    end
  end

  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    redirect_to venues_path
  end

  private

  def venue_params
    params.require(:venue).permit(
      :name,
      :url,
      :address,
      :city,
      :state,
      :zip,
      :capacity
    )
  end

  def authorize_user
    if !user_signed_in?
      raise ActionController::RoutingError.new("NotFound")
    end
  end

  def authorize_admin
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    new_vote = Vote.create(vote_params)
    redirect_to banana_path(new_vote.review.banana)
  end

  def update
    this_vote = Vote.find(params[:id])
    this_vote.up_or_down = if this_vote.up_or_down === "upvote"
                             "downvote"
                    it(
      :user_id,
      :review_id,
      :up_or_down
    )
  end
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_errors(object, field_name)
    error_array = []
    if object.errors.any?
      object.errors.full_messages.each do |error|
        if error.include?(field_name)
          error_array << error
        end
      end
      return error_array.join(", ")
    end
    return nil
  end
end

app/views/admins/index.html.erb
<h1>Admin Console</h1>

<%= link_to "Maintain Venues",  venues_path, class: 'button' %> <br/>
<%= link_to "Maintain Users",  users_path, class: 'button' %>

app/views/home/index.html.erb
<div class="row">
  <div id='app'/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venview</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://use.fontawesome.com/<%= ENV["FONTAWESOME_KEY"] %>.js"></script>
    <script src="https://maps.google.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS_KEY"] %>"
      type="text/javascript"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav class="scrollhide-nav">
      <div class="top-bar">
        <div class="top-bar-left">
          <ul class="menu">
            <li class="menu-text">
              <%= link_to "VenView", root_path %>
            </li>
            <li>
              <%= link_to "Venues", venues_path %>
            </li>
            <li>
              <%= form_tag(venues_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search VenView", class: "search-bar"%>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="top-bar-right">
          <ul class="menu sign-up">
            <li> <a href='https://twitter.com/venview' target="_blank"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a> </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to "Signed In As #{current_user.first_name}",
                  user_path(current_user)
                %>
              </li>
              <li>
                <% if current_user.admin? %>
                  <%= link_to "Admin Console", admins_path, class: "button" %>
                <% end %>
              </li>
              <li>
                <%= link_to "Sign Out",
                  destroy_user_session_path, method: :delete
                %>
              </li>
            <% else %>
              <li> <%= link_to "Sign In", new_user_session_path %> </li>
              <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class='row'>
      <div class='columns content'>
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/reviews/edit.html.erb
<div class='review-box'>

<h1 class='new-header'> Edit Review Form </h1>

<%= form_for (@review) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <p class='error'><%= show_errors(@review, 'Title') %></p>

    <%= f.label :cost %>
    <%= f.collection_radio_buttons :cost, @ratings_collection, :first, :last %>

    <%= f.label :sound_quality, 'Sound Quality' %>
    <%= f.collection_radio_buttons :sound_quality, @ratings_collection, :first, :last %>

    <%= f.label :parking, 'Parking/Accessibility' %>
    <%= f.collection_radio_buttons :parking, @ratings_collection, :first, :last %>

    <%= f.label :body, 'Comments' %>
    <%= f.text_area :body %>

    <div class='submit-container'>
      <%= f.submit "Submit Changes" %>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class='review-box'>

  <h1 class='new-header'> New Review Form </h1>

  <%= form_for ([@venue, @review]) do |f| %>

    <div class='row'>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <p class='error'><%= show_errors(@review, 'Title') %></p>
    </div>

    <div class='row'>
        <%= f.label :cost %>
        <%= f.collection_radio_buttons :cost, @ratings_collection, :first, :last%>
    </div>

    <div class='row'>
      <%= f.label :sound_quality, 'Sound Quality' %>
        <%= f.collection_radio_buttons :sound_quality, @ratings_collection, :first, :last %>
    </div>

    <div class='row'>
      <%= f.label :parking, 'Parking/Accessibility' %>
      <%= f.collection_radio_buttons :parking, @ratings_collection, :first, :last %>
    </div>

    <div class='row'>
      <%= f.label :body, 'Comments' %>
      <%= f.text_area :body %>
    </div>

    <div class='submit-container'>
      <%= f.submit "Submit Review" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='edit-profile-box'>

  <h1> Edit Your Profile </h1>

  <%= form_for @user do |f| %>

    <%= f.label :email, "Email" %>
    <%= f.email_field :email, autofocus: true, :input_html => { :value => @user.email } %>

    <%= f.label :profile_pic_url, "Avatar" %>
    <%= f.text_field :profile_pic_url %>

    Or you can upload your own avatar!
    <%= f.label :avatar, "Avatar Upload" %>
    <%= f.file_field :avatar %>

    Delete my avatar
    <%= check_box_tag "delete-avatar", "1"%><br/>

    <div class='submit-container'>
      <%= f.submit "Update Profile", class: "button" %>
    </div>
  <% end %>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
      <p><%= error %></p>
    <% end %>
  <% end %>

app/views/users/index.html.erb
<h1>List of Users</h1>

<% @users.each do |user| %>
  <% name = "#{user.first_name} #{user.last_name}" %> <br/>
  <%= link_to name, user_path(user) %>
  <% if user === current_user %>
    (this is you!)
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <!-- Top banner dispay of UserName/Avatar/Email -->
  <h1 class='small-10 medium-3 columns text-left profile-header'> <%= @user.first_name %> <%= @user.last_name %> </h1>
  <% if @user.avatar.medium.url === nil %>
    <img src= "<%= @user.profile_pic_url %>" />
  <% else %>
    <%= image_tag @user.avatar.thumb.url %>
  <% end %>
</div>
<div class='row'>
  <h1 class='small-10 medium-3 columns text-right profile-email'> <%= @user.email %> </h1>
</div>
<!-- ADMIN CONTROLS - - Edit | Delete Profile -->
<div class="row">
  <div class="columns small-10 medium-4 text-center">
    <br/>
    <% if !current_user.admin? %>
      <%= link_to 'Edit Profile', edit_user_path(@user), class: 'button float-left' %>
      <%= link_to "Delete Your Account", user_registration_path, :method => :delete, class: 'button' %>
    <% elsif current_user.admin? %>
      <%= link_to "Delete User's Account", user_path, :method => :delete, class: 'button' %>
    <% end %>
  </div>
</div>

<% if @reviews.size > 0 %>

  <!-- Users Review Header -->
  <div class="row">
    <br/>
    <h3 class='small-12 columns text-left profile-header'><strong>My Reviews</strong></h3>
    <div class='small-12 columns'>
      <hr/>
    </div>
  </div>

  <!-- List of all reviews tied to this user (Total Vote Score, Title, Date, Ratings, Content)-->
  <% @reviews.each do |review| %>

    <div class="row venue-showpage-details">
      <div class="small-2 columns medium-1 text-center">
        <strong>Votes:</strong>
        <% total_upvotes = Vote.where({ review_id: review.id, up_or_down: "upvote" }).size %>
        <% total_downvotes = Vote.where({ review_id: review.id, up_or_down: "downvote" }).size %>
        <span class='votes-number'><%= total_upvotes - total_downvotes %></span>
      </div>

      <!-- Listing of Review Title and Date Created -->
      <div class="columns small-5">
        <p>
          <span class='review-title'><%= review.title %></span><br />
          <span class='review-timestamp'><%= review.created_at.strftime("%B %d %Y") %></span><br />
          <% if review.cost %>
            <span class='review-radio'>Cost:</span>   <span class='review-radio-content'><%= review.cost %></span><br />
          <% end %>
          <% if review.sound_quality %>
            <span class='review-radio'>Sound:</span> <span class='review-radio-content'><%= review.sound_quality %></span><br/>
          <% end %>
          <% if review.parking %>
            <span class='review-radio'>Parking</span> <span class='review-radio-content'><%= review.parking %></span><br />
          <% end %>
          <%= review.body %>
        </p>
      </div>

      <!-- Edit and Delete Buttons (Edit is only for ADMIN) -->
      <% if current_user === @user %>
        <div class="columns small-10 medium-3 text-center">
          <%= link_to 'Edit Review', edit_review_path(review), class: 'button float-left'  %>
          <%= link_to 'Delete Review', review_path(review), method: :delete, class: 'button float-right'  %>
        </div>
      <% end %>
    </div>
    <br>
  <% end %>
<% end %>

app/views/venues/edit.html.erb
<div class='form-box'>

  <h1 class='new-header'>Edit Venue Form</h1>

  <%= form_for @venue, :html => { :class => 'venue-form'} do |f| %>

    <div class='row'>
      <%= f.label :name, "Name"%>
      <%= f.text_field :name, :autofocus=>true %>
      <p class='error'><%= show_errors(@venue, 'Name') %></p>
    </div>

    <div class='row'>
      <%= f.label :url, "Website" %>
      <%= f.text_field :url %>
      <p class='error'><%= show_errors(@venue, 'Url') %></p>
    </div>

    <div class='row'>
      <%= f.label :address, "Address" %>
      <%= f.text_field :address %>
      <p class='error'><%= show_errors(@venue, 'Address') %></p>
    </div>

    <div class='row'>
      <%= f.label :city, "City" %>
      <%= f.text_field :city %>
      <p class='error'><%= show_errors(@venue, 'City') %></p>
    </div>

    <div class='row'>
      <%= f.label :state, "State" %>
      <%= f.collection_select :state, @state_collection, :first, :last %>
      <p class='error'><%= show_errors(@venue, 'State') %></p>
    </div>

    <div class='row'>
      <%= f.label :zip, "Zip" %>
      <%= f.text_field :zip %>
      <p class='error'><%= show_errors(@venue, 'Zip') %></p>
    </div>

    <div class='row'>
      <%= f.label :capacity, "Capacity" %>
      <%= f.text_field :capacity %>
    </div>
    <br>

    <div class='submit-container'>
      <%= f.submit :id=>"create-venue" %>
    </div>
  <% end %>
</div>

app/views/venues/index.html.erb
<div class='row'>
  <div class='small-10 medium-4 small-centered text-center columns venue-label'>
    <h1>Our Venues!</h1>
  </div>
</div>


<div class="row">
  <% @venues.each do |venue| %>
    <% if venue == @venues.last %>
      <div class="small-10 medium-5 large-3 columns venue-box end">
      <%= link_to venue.name, venue_path(venue) %><br/>
      </div>
    <% else %>
      <div class="small-10 medium-5 large-3 columns venue-box">
      <%= link_to venue.name, venue_path(venue) %><br/>
      </div>
    <% end %>
  <% end %>

  <% if @venues.blank? %>
  <h4>No Results for: <%= params[:search] %>.</h4>
  <% end %>
</div>


<br />

<div class='add-venue'>
  <%= link_to "Add a New Venue", new_venue_path, class: 'button' %>
</div>

app/views/venues/new.html.erb
<div class='form-box'>

  <h1 class='new-header'>New Venue Form</h1>

  <%= form_for @venue, :html => { :class => 'venue-form'} do |f| %>

    <div class='row'>
      <%= f.label :name, "Name"%>
      <%= f.text_field :name, :autofocus=>true %>
      <p class='error'><%= show_errors(@venue, 'Name') %></p>
    </div>

    <div class='row'>
      <%= f.label :url, "Website" %>
      <%= f.text_field :url %>
      <p class='error'><%= show_errors(@venue, 'Url') %></p>
    </div>

    <div class='row'>
      <%= f.label :address, "Address" %>
      <%= f.text_field :address %>
      <p class='error'><%= show_errors(@venue, 'Address') %></p>
    </div>

    <div class='row'>
      <%= f.label :city, "City" %>
      <%= f.text_field :city %>
      <p class='error'><%= show_errors(@venue, 'City') %></p>
    </div>

    <div class='row'>
      <%= f.label :state, "State" %>
      <%= f.collection_select :state, @state_collection, :first, :last %>
      <p class='error'><%= show_errors(@venue, 'State') %></p>
    </div>

    <div class='row'>
      <%= f.label :zip, "Zip" %>
      <%= f.text_field :zip %>
      <p class='error'><%= show_errors(@venue, 'Zip') %></p>
    </div>

    <div class='row'>
      <%= f.label :capacity, "Capacity" %>
      <%= f.text_field :capacity %>
    </div>
    <br>

    <div class='submit-container'>
      <%= f.submit :id=>"create-venue" %>
    </div>
  <% end %>
</div>

app/views/venues/show.html.erb
<div class='row'>
  <div class='small-10 small-centered text-centered columns'>
    <% if current_user && current_user.admin? %>
    <%= link_to "Update Venue", edit_venue_path(@venue), class: 'button' %>
    <%= link_to "Delete Venue", venue_path(@venue), method: :delete, class: 'button' %>
    <% end %>
  </div>
</div>

<div class='row'>
  <h1 class='columns showpage-venue-name small-10 medium-4 small-centered text-center venue-showpage-details'><%= @venue.name %></h1>
  <% if @venue.url? %>
    <p class='showpage-link small-10 small-centered text-center'><a href="<%=@venue.url%>">Venue Website</a></p>
  <% end %>
</div>
<br />

<div class='row'>
  <div class='venue-address-box small-10 medium-4 small-centered columns text-center venue-showpage-details'>
    <strong>Venue Address:</strong>
    <p>
      <%= @venue.address %><br/>
      <%= @venue.city %>, <%= @venue.state %> <%= @venue.zip %>
    </p>
    <% if @venue.capacity != '' %>
      <strong>Capacity:</strong> <%= @venue.capacity %>
      <br />
    <% end %>
      <br>
    <%= link_to 'Add New Review', new_venue_review_path(@venue), class: 'button add-review' %><br/>
  </div>
</div>
<br>

<div class='row'>
  <div class='small-10 medium-4 small-centered columns map-container' id='map'>
  </div>
  <br />
</div>

<hr />

<% @reviews.each do |review| %>
  <div class="row review-container">
    <div class="columns small-5 medium-1">
      <strong>Votes: </strong>
      <% total_upvotes = Vote.where({ review_id: review.id, up_or_down: "upvote" }).size %>
      <% total_downvotes = Vote.where({ review_id: review.id, up_or_down: "downvote" }).size %>

      <!-- print the actual number of votes -->
      <%= total_upvotes - total_downvotes %>
    </div>

    <!-- Upvote / Downvote Section -->
    <div class="row">
      <div class="small-1 medium-4 columns votes">
        <% this_vote = Vote.find_by(user: current_user, review: review) %>
        <% if current_user && !this_vote %>
          <%= link_to '', votes_path(:vote => { user_id: current_user.id, review_id: review.id, up_or_down: "upvote"}), method: :post, class: 'triangle-up' %>
          <%= link_to '', votes_path(:vote => { user_id: current_user.id, review_id: review.id, up_or_down: "downvote"}), method: :post, class: 'triangle-down' %>
        <% elsif current_user && this_vote.up_or_down === "upvote" %>
          <%= link_to '', vote_path(this_vote), method: :delete, class: 'triangle-up' %><br/>
          <%= link_to '', vote_path(this_vote), method: :put, class: 'triangle-down' %>
        <% elsif current_user && this_vote.up_or_down === "downvote" %>
          <%= link_to '', vote_path(this_vote), method: :put, class: 'triangle-up' %><br/>
          <%= link_to '', vote_path(this_vote), method: :delete, class: 'triangle-down' %>
        <% end %>
      </div>
    </div>

    <!-- Vote Body (Description and Details) -->
    <div class="columns small-10 medium-8">
      <br/>
      <p>
        <%= review.title %><br />
        Submitted: <%= review.created_at.strftime("%B %d %Y") %><br />
        <% if review.cost %>
          <strong>Cost:</strong> <%= review.cost %><br />
        <% end %>
        <% if review.sound_quality %>
          <strong>Sound Quality:</strong> <%= review.sound_quality %><br/>
        <% end %>
        <% if review.parking %>
          <strong>Parking/Accessibility</<strong> <%= review.parking %><br />
        <% end %>
        <%= review.body %>
      </p>
    </div>

    <!-- Buttons for Edit & Delete -->
    <div class="columns small-10 medium-2">
      <% if current_user && review.user_id == current_user.id %>
        <%= link_to 'Edit Review', edit_review_path(review), class: 'button' %><br/>
      <% end %>
      <% if current_user && (review.user_id == current_user.id || current_user.admin?) %>
        <%= link_to 'Delete Review', review_path(review), method: :delete, class: 'button' %>
      <% end %>
    </div>
  </div>

  <hr/>
  <!-- <br/> -->
<% end %>

<div class='row'>
  <div class='small-10 small-centered text-center'>
    <%= link_to 'Back to Venues', venues_path, class: 'button'%>
  </div>
</div>

<script type="text/javascript">
  var venue_name = '<%= @venue.name %>';
  var venue_address = '<%= @venue.address %>';
  var venue_city = '<%= @venue.city %>';
  var venue_state = '<%= @venue.state %>';
  var venue_zip = '<%= @venue.zip %>';

  var address = `${venue_address}, ${venue_city}, ${venue_state} ${venue_zip}`;

  var map = new google.maps.Map(document.getElementById('map'), {
    mapTypeId: google.maps.MapTypeId.TERRAIN,
    zoom: 15
  });

  var geocoder = new google.maps.Geocoder();

  geocoder.geocode({
    'address': address
  },

  function(results, status) {
    if(status == google.maps.GeocoderStatus.OK) {
      new google.maps.Marker({
        position: results[0].geometry.location,
        map: map
      });
      map.setCenter(results[0].geometry.location);
    }
  });
</script>